pr: none
trigger: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  - name: BuildingInVsts
    value: true
  - name: SolutionDirectory
    value: 'src\FiscalIntegration\EFRSample'

steps:

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.4.0'
    inputs:
      versionSpec: '5.4.0'

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      feedsToUse: config
      nugetConfigPath: nuget.config

  - task: VSBuild@1
    displayName: 'Build solution EFRSample.sln'
    inputs:
      solution: '$(Build.SourcesDirectory)\$(SolutionDirectory)\EFRSample.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Install AzureSignTool'
    inputs:
      command: custom
      custom: tool
      arguments: 'install --global azuresigntool'

  - task: PowerShell@2
    displayName: 'Copy CloudScaleUnitExtensionPackage package to artifact directory'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowershellScripts/CopyFileToDestination.ps1
      arguments: '-RelativePath "$(Build.SourcesDirectory)\$(SolutionDirectory)\ScaleUnit" -File "CloudScaleUnitExtensionPackage.zip" -DestinationFullName "$(Build.ArtifactStagingDirectory)\ScaleUnitPackage_$(Build.BuildNumber).zip"'

  - task: PowerShell@2
    displayName: 'Copy Hardware Station Installer to Artifact directory'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowerShellScripts/CopyFileToDestination.ps1
      arguments: '-RelativePath "$(Build.SourcesDirectory)\$(SolutionDirectory)\HardwareStation.Installer" -File "Contoso.EFRSample.HardwareStation.Installer.exe" -DestinationFullName "$(Build.ArtifactStagingDirectory)\Contoso.EFRSample.HardwareStation.Installer_$(Build.BuildNumber).exe"'

  - task: PowerShell@2
    displayName: 'Copy Scale Unit Installer to Artifact directory'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowerShellScripts/CopyFileToDestination.ps1
      arguments: '-RelativePath "$(Build.SourcesDirectory)\$(SolutionDirectory)\ScaleUnit.Installer" -File "Contoso.EFRSample.ScaleUnit.Installer.exe" -DestinationFullName "$(Build.ArtifactStagingDirectory)\Contoso.EFRSample.ScaleUnit.Installer_$(Build.BuildNumber).exe"'

  - task: PowerShell@2
    displayName: 'Copy Modern POS Installer to Artifact directory'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowerShellScripts/CopyFileToDestination.ps1
      arguments: '-RelativePath "$(Build.SourcesDirectory)\$(SolutionDirectory)\StoreCommerce.Installer" -File "Contoso.EFRSample.StoreCommerce.Installer.exe" -DestinationFullName "$(Build.ArtifactStagingDirectory)\Contoso.EFRSample.StoreCommerce.Installer_$(Build.BuildNumber).exe"'

  - task: PowerShell@2
    displayName: 'Sign Files'
    inputs:
      targetType: filePath
      filePath: ./Pipeline/PowerShellScripts/CodeSign.ps1
      arguments: '-TenantId $(TenantId) -ApplicationId $(ApplicationId) -ApplicationSecretValue $(SecretValue) -AzureKeyVaultURI $(AzureKeyVaultURI) -CertificateName $(CertificateName) -Timestamp $(Timestamp) -TimestampDigest "sha256" -Files "$(Build.ArtifactStagingDirectory)\Contoso.EFRSample.HardwareStation.Installer_$(Build.BuildNumber).exe $(Build.ArtifactStagingDirectory)\Contoso.EFRSample.ScaleUnit.Installer_$(Build.BuildNumber).exe $(Build.ArtifactStagingDirectory)\Contoso.EFRSample.StoreCommerce.Installer_$(Build.BuildNumber).exe"'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
